kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-influxdb
  labels:
    type: local
    app: my-release-influxdb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/clusterfs/K3SPV/influxdb"
