apiVersion: v1
appVersion: "1.12"
description: Telegraf is an agent written in Go for collecting, processing, aggregating,
  and writing metrics.
engine: gotpl
home: https://www.influxdata.com/time-series-platform/telegraf/
keywords:
- telegraf
- collector
- timeseries
- influxdata
maintainers:
- email: naseemkullah@gmail.com
  name: naseemkullah
name: telegraf
version: 1.5.0
